version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: nodopay_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nodopay_db
      MYSQL_USER: nodopay_user
      MYSQL_PASSWORD: nodopay_password
    ports:
      - "3306:3306"
    volumes:
      # Mount your SQL initialization file
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Persist MySQL data
      - mysql_data:/var/lib/mysql
    networks:
      - nodopay_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Your .NET API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodopay_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=nodopay_db;Uid=nodopay_user;Pwd=nodopay_password;
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - nodopay_network

# Named volumes for data persistence
volumes:
  mysql_data:

# Custom network for service communication
networks:
  nodopay_network:
    driver: bridge